### ISSUE TITLE
Running Node Discaptcha results in a module error

### ISSUE THREAD

**Issue by alexmoerschbacher** [ahoys/discaptcha#24]
After going through steps 1-7 and making it to step 8 running `node discaptcha` gives the following error:
![image](https://user-images.githubusercontent.com/48182004/127900674-5539724a-3337-4a8d-9a15-9e20f3342d38.png)

**Comment by ahoys** [comment]
That error means that the script you are trying to execute (discaptcha) doesn't exist in the folder where you are currently in.
- Is your command line's path correct? Should it be just C:\repos\discaptcha? You have discaptcha twice.
- Does the discaptcha.js file actually exist in that path?
- Make sure you have extracted the released package [https://github.com/ahoys/discaptcha/releases/download/v.2.1.0/Discaptcha-v.2.1.0.zip](https://github.com/ahoys/discaptcha/releases/download/v.2.1.0/Discaptcha-v.2.1.0.zip), not the GitHub repository. The package is built, the repository is not.

The folder should look like this:

![image](https://user-images.githubusercontent.com/14974945/127917299-ac645086-903d-4b3c-a19d-8a958c8dcb65.png)

**Comment by alexmoerschbacher** [comment]
Thank you for the quick response, I was using the repository not the released package. What would the steps be if I wanted to make changes to the repository and then build it? I mainly use javascript, not typescript so I'm not familiar with the steps.

**Comment by ahoys** [comment]
If you'd like to develop Discaptcha further, you should clone the repository (like you probably did the first time), run yarn install in the repository folder and then code with your code editor of choice (the best fit would be Visual Studio Code with Prettier & TSLint extensions). The file src/discaptcha.ts is the core file where most of the magic is happening.

"yarn build" builds the project, translating all the code into a packaged JavaScript bundle. This creates a new directory called "build". There you'll find your finalized build.
"yarn start" starts the project in a development mode (Use "discaptcha/dev.env" file to input development environment variables, similar to ".env" file)
"yarn lint" lints the code (makes formatting coherent & pretty)

TypeScript actually doesn't change much. It just adds typings here and there, making sure the developer can't make silly mistakes. The "yarn build" script uses typescript to build the package (translates the code back to JavaScript, so that Node understands it).
